### ISSUE TITLE
Add Open Contracting Identifier field on metadata template

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_agreement#13]
A new field named **Open Contracting Identifier** (id: open_contracting_id) needs to be added to the metadata form for agreements. this field would be **invisible** and **auto-generated** with the following schema:

**ocds-miumsd-CKAN_UNIQUE_ID**

CKAN_UNIQUE_ID is the id CKAN automatically assigns to each record

**Comment by prustar** [comment]
@acorbi - The field is invisible to the data staff but needs to be exposed on the front end for people doing research. This helps them to verify if documents are the same.

**Comment by acorbi** [comment]
@prustar jup, that is the intention
