### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by vatana92** [OpenDevelopmentMekong/ckanext-odm_agreement#6]
I have translated this MoU from English to Khmer, and published it. When I switch from Khmer site to English site, the page not found. 
Link to that record: https://data.opendevelopmentmekong.net/km/agreement/lian-heng-trading-co-ltd
![screenshot_6](https://cloud.githubusercontent.com/assets/19201022/23299532/711c42a2-fab4-11e6-8e41-c9af12d7b8c4.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/19201022/23299531/7119ce00-fab4-11e6-943f-2f437af9a910.png)

**Comment by vatana92** [comment]
Also, I don't like to click/select the company name again and again on Contracting Parties each time I go to edit the information of the record. It's annoying when I can't update new information, and what I have filled are lost.  
![screenshot_9](https://cloud.githubusercontent.com/assets/19201022/23299970/1d49d502-fab6-11e6-9f0c-e5f15fc58601.png)

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/commit/2efa8a4aa107357a4f7ac35157ff0cbe24d89bb1

@vatana92 please test on PROD and provide feedback
